stable 9.6: push bugfix from dev to stable build
6d49e295 fix install_from_github func
361e122e impl https://github.com/Ansuel/tch-nginx-gui/issues/945
779cf3c3 gui: move gui upgrade option as the first option
98b79a91 Revert "gui: move gui upgrade option as the first option"
db965bfe core: add check for mkdir and normalize logging file
3dc5d0c2 gui: move gui upgrade option as the first option
51f5252b }?
753371a6 update changelog issue template
36aff9fc fix syntax error move bank info to modgui modal
d0fe8fa3 remove also mobiled mappers when lib not found more shell
script optimizations
04ecc69e more infos for debug file minor shell warnings for rootdevice
fix https://github.com/Ansuel/tch-nginx-gui/issues/1034
0c0ca39d core: fix error in remove modgui_log dir
ec9e9da4 core: improve loggin of data
2bc05f59 core: move console echo to dedicated function
431e48a5 syntax error
db8730f9 force bank1 erase and reboot also on first install from bank2
check /proc/prozone is exposed before tricking failboot to avoid
warnings
5d48b3a9 fix feeds for 17.1/2 arm added macoers feeds for arm 18.x
update DGA (arm) specific package embedded ipk fix mv scripthelpers
warnings during install on some devices remove mobiled card on
unsupported devices (mobiled not installed)
a5f2b677 fix "1" echo during install
549568e0 fix perm
669b508f missing source file
bab60ea8 github: fix typo in README (#1026)
f38c4aa4 typo
2718536e fixes login for opkg repo feed fix logger_command: not found
during specific package install
0689a055 make specific_app cases more generic on cpu type
1e76fbab fix luci install on some firmwares
22a65191 rework extensions install checks to use marketing_version and
cputype
318d7819 gui: fix wireless-client-modal broken in minified source
eefa1fef move custom func to modgui modal remove transfer bank clone
bank
44f2bd31 gui: fix typo in serial modem for missing input box
7c5089c4 gui: permit to force a different modem serial
9ae6fee7 gui: improve cwmp settings in modgui modal
cc1ea837 gui: drop use of cwmp TIM latest version
0007ffce gui: Add new option to disable cwmp update
5c575439 gui: fix bad cwmp tim version
c1650eb8 gui: also export Kernel version in modgui mapper
43ea509f gui: export CPUtype in modgui mapper
fdac82da xdsl drivers: add A2pvfbH046w B2pvfbH046w
a2ce5dd0 remove hardcoded version from rootdevice
3986f23f typo
27f20328 core: disable switchover for cwmp
49281c6c core: skip bank_1 erase if it doesn't contain a valid firmware
9c38099f gui: drop use of driver_version to store xdsl firmware version
6f318fb8 gui: remove use of versioncustom latest config
2b262db7 gui: remove use of gui_version in modgui config
fa5333d0 gui: move gui version to rpc mapper
4787ef78 core: add option to disable modoverlay
317b3959 core: force otp to second bank
d9210a9e improve feeds detection
3ab577c9 core: force second bank on firmware upgrade
5e5dcd1c core: fix typo in cwmpd upgrade script
e6506fdb shellcheck avoid subshell spawning
fb149c3c core: refresh firmware upgrade script
da64dfce core: refresh cwmpd upgrade script
708bedf2 core: fix wrong preinit check
e8091fbc core: update core file on gui upgrade
80094ba2 Fixed FEC translations (#1016)

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

diff --git a/decompressed/base/etc/init.d/do_migrate_overlay b/decompressed/base/etc/init.d/do_migrate_overlay
--- a/decompressed/base/etc/init.d/do_migrate_overlay
+++ b/decompressed/base/etc/init.d/do_migrate_overlay
@@ -1,15 +1,49 @@
 #!/bin/ash /etc/rc.common
 
 START=00
+EXTRA_COMMANDS="preserve_files"
+EXTRA_HELP="        preserve_files  Transfer files from modoverlay to bank"
+
+upperdir=/modoverlay/bank_mod
+overlay_bank=/overlay/bank_2
+
+logging_file=/overlay/modgui_log/migrate_log_$(date +"%H-%M_%m-%d-%y")
+
+create_modgui_log() {
+  [ ! -d /overlay/modgui_log ] && mkdir /overlay/modgui_log
+  touch $logging_file
+}
 
 kecho() {
-	echo "$1"
-	echo "$1" > /dev/kmsg
+  echo mount_root-mod: "$@"
+  echo mount_root-mod: "$@" > /dev/kmsg
+  echo mount_root-mod: "$@" >> $logging_file
+}
+
+preserve_files() {
+    #these files should be moved back to bank_2 overlay to allow our mount hook to take place (and preserve root after boot)
+    local preserve_list="/etc/init.d/rootdevice /etc/rc.d/S94rootdevice /usr/sbin/random_seed /sbin/insmod \
+    /lib/mount_modroot/05_transfer_basefiles /etc/init.d/do_migrate_overlay /usr/sbin/mount_modoverlay /sbin/mount_root-mod"
+
+    if ! mount | grep /modoverlay/bank_mod > /dev/null ; then
+      kecho "Modroot not found. Can't preserve files."
+      exit 1
+    fi
+
+    update_file_if_needed() { # <file> <source> <dest>
+      cmp -s "$2$1" "$3$1" || cp -a "$2$1" "$3$1"
+    }
+
+    for f in $preserve_list; do
+      mkdir -p $overlay_bank$(dirname "$f")
+      # kecho "update_file_if_needed $f"
+      update_file_if_needed "$f" "$upperdir" $overlay_bank
+    done
+
+    sync
 }
 
 boot() {
-  local upperdir=/modoverlay/bank_mod
-  local overlay_bank=/overlay/bank_2
   local ram_dir=/tmp/migrate_overlay
   local upperdir_backup=/tmp/upperdir_backup
   local files_to_del=/files_to_del
@@ -23,20 +57,20 @@ boot() {
     local source=$1
     local dest=$2
 
-    kecho "mount_root-mod: copying $source/* to $dest/ ..."
+    kecho "copying $source/* to $dest/ ..."
 
     for d in $(find $source/ -xdev -type d ! -path "*/modoverlay" -a ! -path "*/saferoot" | cut -d '/' -f4-); do
-      # kecho "mount_root-mod: creating $dest/$d"
+      # kecho "creating $dest/$d"
       mkdir -p "$dest/$d" 2>/dev/kmsg
     done
 
     for f in $(find $source/ -xdev -type f ! -path "*/modoverlay" -a ! -path "*/saferoot" | cut -d '/' -f4-); do
-      # kecho "mount_root-mod: copying $source/$f to $dest/$f"
+      # kecho "copying $source/$f to $dest/$f"
       cp -dp "$source/$f" "$dest/$f" 2>/dev/kmsg
     done
 
     for l in $(find $source/ -xdev -type l ! -path "*/modoverlay" -a ! -path "*/saferoot" | cut -d '/' -f4-); do
-      # kecho "mount_root-mod: copying $source/$l to $dest/$l"
+      # kecho "copying $source/$l to $dest/$l"
       cp -dp "$source/$l" "$dest/$l" 2>/dev/kmsg
     done
   }
@@ -51,7 +85,7 @@ boot() {
     # Now scan for file to be deleted... depending on the system these can be char type file
     # In new system the cp fails to copy this file. To fix this put the file in a txt file and then remove them by reading it
     for c in $(find $source/ -xdev -type c ! -path "*/modoverlay" -a ! -path "*/saferoot" | cut -d '/' -f4-); do
-      # kecho "mount_root-mod: setting /"$c" to be flagged as deleted"
+      # kecho "setting /"$c" to be flagged as deleted"
       echo /"$c" >> $path_to_save_list
     done
   }
@@ -63,13 +97,13 @@ boot() {
     # 2. Clean the deleted file from the old overlay
     # 3. Reboot to make the accessible from the new overlay
     # 4. Remove the file again in the new mounted overlay
-    kecho "mount_root-mod: checking if there are files to be removed..."
+    kecho "checking if there are files to be removed..."
     if [ -f $files_to_del ]; then
-      kecho "mount_root-mod: there are files scheduled to be removed..."
+      kecho "there are files scheduled to be removed..."
 
       # Actually remove the file flagged as removed in the old overlay
       while read -r file; do
-        # kecho "mount_root-mod: setting "$file" as deleted in the new overlay"
+        # kecho "setting "$file" as deleted in the new overlay"
         rm "$file" 2>/dev/kmsg
       done < "$files_to_del"
 
@@ -80,7 +114,7 @@ boot() {
   }
 
   move_overlay() {
-    kecho "mount_root-mod: checking if overlay must be transfered..."
+    kecho "checking if overlay must be transfered..."
     #use the config folder as check to know that we should populate the modoverlay (mtd3) and cleanup real overlay (mtd2)
     # Other process can write some config file before modoverlay is mounted, checking the config dir is not enough
     # Try to check if modgui exist and assume the migration is needed if present
@@ -99,42 +133,26 @@ boot() {
 
       #at this point we should remove all empty folders in bank_2 overlay, except the modoverlay mountpoint
       for f in "$overlay_bank/"*; do
-        # kecho "mount_root-mod: check-for-rm $f"
+        # kecho "check-for-rm $f"
         [ "$f" != "$overlay_bank/modoverlay" ] && [ "$f" != "$overlay_bank/saferoot" ] && rm -rf "$f"
       done
 
       sync
 
-      kecho "mount_root-mod: migration done!"
+      kecho "migration done!"
 
       need_reboot="1"
     fi
   }
 
-  preserve_files(){
-    #these files should be moved back to bank_2 overlay to allow our mount hook to take place (and preserve root after boot)
-    preserve_list="/etc/init.d/rootdevice /etc/rc.d/S94rootdevice /usr/sbin/random_seed /sbin/insmod \
-    /lib/mount_modroot/05_transfer_basefiles /etc/init.d/do_migrate_overlay /usr/sbin/mount_modoverlay /sbin/mount_root-mod"
-
-    update_file_if_needed() { # <file> <source> <dest>
-      cmp -s "$2$1" "$3$1" || cp -a "$2$1" "$3$1"
-    }
-
-    for f in $preserve_list; do
-      mkdir -p $overlay_bank$(dirname "$f")
-      # kecho "mount_root-mod: update_file_if_needed $f"
-      update_file_if_needed "$f" "$upperdir" $overlay_bank
-    done
-
-    sync
-  }
-
   reboot_if_needed(){
     if [ "$need_reboot" = "1" ]; then
-      # Simulate the bank_1 failed 3 times
-      echo 1 > /proc/prozone/bootfail
-      echo 2 > /proc/prozone/bootcounter
-      echo 0 > /proc/prozone/bootbank
+      [ -d /proc/prozone ] && {
+        # Simulate the bank_1 failed 3 times
+        echo 1 > /proc/prozone/bootfail
+        echo 2 > /proc/prozone/bootcounter
+        echo 0 > /proc/prozone/bootbank
+      }
       reboot && sleep 30
     fi
   }
@@ -142,7 +160,7 @@ boot() {
   if mount | grep /modoverlay/bank_mod > /dev/null ; then
     { check_files_to_delete; move_overlay; preserve_files; reboot_if_needed; }
   else
-    kecho "mount_root-mod: modoverlay not mounted! Aborting migration!"
+    kecho "modoverlay not mounted! Aborting migration!"
   fi
 
   # Restart watchdog
