core: improve loggin of data
Save log files to overlay and schedule to remove them on next boot to
make them accessible. Files will be scheduled to be accessible after a
full boot with the rootdevice script executed.

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

diff --git a/decompressed/base/etc/init.d/rootdevice b/decompressed/base/etc/init.d/rootdevice
--- a/decompressed/base/etc/init.d/rootdevice
+++ b/decompressed/base/etc/init.d/rootdevice
@@ -58,17 +58,46 @@ EOF
 }
 
 ####################LOG FUNCTION#################
+rootdevice_log_file=/tmp/rootdevice_log
+
 kecho() {
-  echo $@ >/dev/console
+  echo "  "$@ >/dev/console
+  echo "  "$@ >>$rootdevice_log_file
 }
 
-logger_command() {
+logecho() {
   if [ "$debug" -eq 1 ]; then
-    logger -t "Root Script" "$1"
-	  echo "Root Script" "$1"
+    logger -t "Root Script" $@
+    echo "Root Script" $@
   fi
+  echo "Root Script" $@ >>$rootdevice_log_file
+}
+
+logecho_always() {
+  logger -t "Root Script" $@
+  echo "Root Script" $@ >>rootdevice_log_file
+}
+
+create_modgui_log() {
+  touch $rootdevice_log_file
+}
+
+save_modgui_log() {
+  mkdir /overlay/modgui_log
+  cp -rf $rootdevice_log_file /overlay/modgui_log/rootdevice_log_$(date +"%H-%M_%m-%d-%y")
+}
+
+sched_remove_modgui_log() {
+  mkdir /overlay/modgui_log.remove_due_to_upgrade
+  mv /overlay/modgui_log/* /overlay/modgui_log.remove_due_to_upgrade/
+  rm /overlay/modgui_log
 }
 #################################################
+
+reboot_save() {
+  save_modgui_log
+  reboot
+}
 
 disable_upload_coredump_and_reboot() {
   #disable upload of coredump...
@@ -77,24 +106,24 @@ disable_upload_coredump_and_reboot() {
     uci set system.@coredump[0].action="ignore"
   fi
   if [ "$(uci get -q system.@coredump[0].reboot)" != "0" ]; then
-    logger_command "Disable reboot after crash, this gives race condition..."
+    logecho "Disable reboot after crash, this gives race condition..."
     uci set system.@coredump[0].reboot='0'
   fi
   #Clean coredump
   if [ "$(find /root -type f -name "*.core.*")" ]; then
     for coredump in /root/*.core.*; do
-      logger_command "Removing coredump $coredump from /root..."
+      logecho "Removing coredump $coredump from /root..."
       rm "$coredump"
     done
   fi
 }
 
 enable_serial_console() {
-	#Enable hardware serial console to intercept bootloops
-	if grep -q '#::askconsolelate' /etc/inittab; then
-    logger_command "Enabling hardware serial console..."
-	  sed -i 's/#//' /etc/inittab
-	fi
+  #Enable hardware serial console to intercept bootloops
+  if grep -q '#::askconsolelate' /etc/inittab; then
+    logecho "Enabling hardware serial console..."
+    sed -i 's/#//' /etc/inittab
+  fi
 }
 
 check_and_apply_root() {
@@ -117,39 +146,39 @@ check_and_apply_root() {
     uci commit modgui
   }
 
-  logger_command "Saving hashed root password in uci if modified..."
+  logecho "Saving hashed root password in uci if modified..."
 
   #Enable root access to the real shell (default is /bin/restricted_shell)
   if [ "$(awk -F: '/root/ {print $7 }' /etc/passwd)" != "/bin/ash" ]; then
-    logger_command "Enabling ash shell to root..."
+    logecho "Enabling ash shell to root..."
     sed -i 's#/root:.*$#/root:/bin/ash#' /etc/passwd
   fi
 
   if [ -n "$saved_encrypted_pass" ]; then
     if [ "$encrypted_pass" != "$saved_encrypted_pass" ]; then
       if [ -f /root/.reapply_due_to_upgrade ]; then
-        logger_command "Setting root password from password saved in config"
+        logecho "Setting root password from password saved in config"
         kecho "Setting root password from password saved in config"
         major_system_version="$(uci get version.@version[0].marketing_version | sed 's#\.##' | grep -o -E '[0-9]+')"
         #firmware 16.x store a stripped 13char hash (not salted) that cannot be migrated to >=17.x (and viceversa)
         if { [ ${#saved_encrypted_pass} -le 13 ] && [ "$major_system_version" -lt 170 ]; } || { [ ${#saved_encrypted_pass} -gt 13 ] && [ "$major_system_version" -ge 170 ]; }; then
           sed -i -e "s:^root\:[^\:]*\::root\:$saved_encrypted_pass\::" /etc/shadow
         else
-          logger_command "Incompatible password saved in config, resetting password to root!"
+          logecho "Incompatible password saved in config, resetting password to root!"
           kecho "Incompatible password saved in config, resetting password to root!"
           echo -e "root\nroot" | passwd >/dev/null
         fi
       else
-        logger_command "Shadow contains different pass than saved one. Save it!"
+        logecho "Shadow contains different pass than saved one. Save it!"
         kecho "Shadow contains different pass than saved one. Save it!"
         store_pass_in_uci
       fi
     else
-      logger_command "Changed-and-ucisaved root password detected!"
+      logecho "Changed-and-ucisaved root password detected!"
       kecho "Changed-and-ucisaved root password detected!"
     fi
   else
-    logger_command "Resetting password to root..."
+    logecho "Resetting password to root..."
     kecho "Resetting password to root..."
     #Set the password to root as we have an unknown password
     echo -e "root\nroot" | passwd >/dev/null
@@ -160,14 +189,14 @@ check_and_apply_root() {
     store_pass_in_uci
   fi
 
-  logger_command "Checking and force-enabling dropbear SSH Server for root on lan"
+  logecho "Checking and force-enabling dropbear SSH Server for root on lan"
   disable_conflicting_dropbear() {
-      dropbearintf=$(uci get -q dropbear."$1".Interface)
-      dropbearport=$(uci get -q dropbear."$1".Port)
-      [ "$(uci get -q dropbear."$1".enable)" != "0" ] \
-      && { [ "$dropbearintf" = "lan" ] || [ "$dropbearintf" = "" ]; } \
-      && { [ "$dropbearport" = "22" ] || [ "$dropbearport" = "" ]; } \
-      && uci set dropbear."$1".enable=0
+    dropbearintf=$(uci get -q dropbear."$1".Interface)
+    dropbearport=$(uci get -q dropbear."$1".Port)
+    [ "$(uci get -q dropbear."$1".enable)" != "0" ] &&
+      { [ "$dropbearintf" = "lan" ] || [ "$dropbearintf" = "" ]; } &&
+      { [ "$dropbearport" = "22" ] || [ "$dropbearport" = "" ]; } &&
+      uci set dropbear."$1".enable=0
   }
   config_load "dropbear"
   config_foreach disable_conflicting_dropbear dropbear
@@ -186,7 +215,7 @@ check_and_apply_root() {
   uci set "$dropbear_path".enable='1'
 
   if [ "$(uci changes)" ]; then
-    logger_command "Restarting Dropbear SSH Server..."
+    logecho "Restarting Dropbear SSH Server..."
     uci commit dropbear
     /etc/init.d/dropbear enable
     /etc/init.d/dropbear restart >/dev/null
@@ -194,7 +223,7 @@ check_and_apply_root() {
 
   firewall_path=$(uci show firewall | grep -m 1 $(fw3 -q print | egrep 'iptables -t filter -A zone_lan_input -p tcp -m tcp --dport 22 -m comment --comment "!fw3: .+" -j DROP' | sed -n -e 's/^iptables.\+fw3: \(.\+\)".\+//p') 2>/dev/null | sed -n -e "s/\(.\+\).name='.\+'$//p" 2>/dev/null)
   if [ "$firewall_path" ]; then
-    logger_command "Restarting firewall cleaned from SSH drop rule..."
+    logecho "Restarting firewall cleaned from SSH drop rule..."
     uci -q set "$firewall_path".target='ACCEPT'
     /etc/init.d/firewall reload 2>/dev/null
   fi
@@ -205,16 +234,16 @@ install_gui() {
   [[ -z "$log_progress" ]] && log_progress=0
   [[ -z "$restart_dnsmasq" ]] && restart_dnsmasq=0
 
-  logger -s -t 'Root Script' "Installing in progress..."
+  logecho_always "Installing in progress..."
 
-  logger_command "Start rooting"
+  logecho "Start rooting"
   if [ ! -f /root/.install_gui ]; then #this check if the placeholder exist
-    touch /root/.install_gui #this is a placeholder to know if the install process ends correctly (removed by 99_postreq.sh)
+    touch /root/.install_gui           #this is a placeholder to know if the install process ends correctly (removed by 99_postreq.sh)
   fi
 
   if [ -d /etc/modgui_scripts ]; then
     for file in /etc/modgui_scripts/*; do
-      logger_command "Executing $file"
+      logecho "Executing $file"
       . $file
     done
   fi
@@ -224,7 +253,7 @@ install_gui() {
     rm /root/.reapply_due_to_upgrade
   fi
 
-  logger_command "Process complete. tch-nginx-gui is now installed!"
+  logecho "Process complete. tch-nginx-gui is now installed!"
   kecho "Process complete. tch-nginx-gui is now installed!"
 }
 
@@ -233,15 +262,14 @@ is_dual_bank() {
 }
 
 get_bank_mtd() {
-  cat /proc/mtd  | grep \"$1\" | sed 's/:.*//'
+  cat /proc/mtd | grep \"$1\" | sed 's/:.*//'
 }
 
-
-safe_mv(){ # <src file path> <dest file path>
+safe_mv() { # <src file path> <dest file path>
   # if destination file exist will be forcely removed before the free space check
   [ -f "$2" ] && rm "$2"
   # mv will be skipped if not enought space!
-  [ "$(df -P "$(dirname "$2")" | awk 'NR==2 {print $4}')" -gt "$(($(wc -c < "$1") / 1024))" ] && mv "$1" "$2" || echo "ERROR: No space left for mv $1 $2"
+  [ "$(df -P "$(dirname "$2")" | awk 'NR==2 {print $4}')" -gt "$(($(wc -c <"$1") / 1024))" ] && mv "$1" "$2" || echo "ERROR: No space left for mv $1 $2"
 }
 
 erase_bank1_reboot() { # <bootedbank>
@@ -249,32 +277,32 @@ erase_bank1_reboot() { # <bootedbank>
   [ -f /tmp/GUI.tar.bz2 ] && safe_mv /tmp/GUI.tar.bz2 /root/GUI.tar.bz2
   [ -f /tmp/GUI_dev.tar.bz2 ] && safe_mv /tmp/GUI_dev.tar.bz2 /root/GUI.tar.bz2
   if [ ! "$(uci -q get modgui.gui.gui_hash)" ]; then
-    logger_command "Seems first install from $1 saving GUI to root and setting install flags..."
+    logecho "Seems first install from $1 saving GUI to root and setting install flags..."
     kecho "Seems first install from $1 saving GUI to root  and setting install flags..."
     touch /root/.reapply_due_to_upgrade
     touch /root/.install_gui
   fi
   # Moving running overlay to bank2 if we are on bank1
   [ "$1" == "bank_1" ] && {
-    logger_command "Moving /overlay/bank_1 to /overlay/bank_2..."
+    logecho "Moving /overlay/bank_1 to /overlay/bank_2..."
     kecho "Moving /overlay/bank_1 to /overlay/bank_2..."
     mv /overlay/bank_1 /overlay/bank_2
   }
-  logger_command "Activating and erasing bank_1..."
+  logecho "Activating and erasing bank_1..."
   kecho "Activating and erasing bank_1..."
-  echo bank_1 > /proc/banktable/active
+  echo bank_1 >/proc/banktable/active
   # Reboot to first valid firmware
-  logger_command "Installation will continue after reboot..."
+  logecho "Installation will continue after reboot..."
   kecho "Installation will continue after reboot..."
   [ -d /proc/prozone ] && {
     # Simulate the bank_1 failed 3 times
-    echo 1 > /proc/prozone/bootfail
-    echo 2 > /proc/prozone/bootcounter
-    echo 0 > /proc/prozone/bootbank
+    echo 1 >/proc/prozone/bootfail
+    echo 2 >/proc/prozone/bootcounter
+    echo 0 >/proc/prozone/bootbank
   }
   sync
   mtd -r erase bank_1
-  reboot
+  reboot_save
   exit 0
 }
 
@@ -289,7 +317,7 @@ check_and_apply_obp() {
     #we must initialize the check_obp var as is not found
     if [ -f "$notbooted_modgui_configfile" ]; then
       #if we are in a clean bank_2 overlay but in the notbooted bank overlay there was a modgui config file restore var from it
-      get_config_notbooted=$(< "$notbooted_modgui_configfile" grep check_obp | awk '{print $3}' | sed "s/'//g")
+      get_config_notbooted=$(grep <"$notbooted_modgui_configfile" check_obp | awk '{print $3}' | sed "s/'//g")
       if [ -n "$get_config_notbooted" ] && [ ! "$(uci -q get modgui.var.check_obp)" ]; then
         uci set modgui.var.check_obp="$get_config_notbooted"
         uci commit modgui
@@ -305,30 +333,30 @@ check_and_apply_obp() {
 
     activeversion=$(cat /proc/banktable/activeversion)
     if [ "$activeversion" != "Unknown" ]; then
-      logger_command "OBP check: looks like passive bank have a valid version: $activeversion"
+      logecho "OBP check: looks like passive bank have a valid version: $activeversion"
       kecho "OBP check: looks like passive bank have a valid version: $activeversion"
     else
       [ -d /proc/prozone ] && {
         # Simulate the bank_1 failed 3 times
-        echo 1 > /proc/prozone/bootfail
-        echo 2 > /proc/prozone/bootcounter
-        echo 0 > /proc/prozone/bootbank
+        echo 1 >/proc/prozone/bootfail
+        echo 2 >/proc/prozone/bootcounter
+        echo 0 >/proc/prozone/bootbank
       }
     fi
 
     [ -d "/overlay/bank_1" ] && rm -rf "/overlay/bank_1"
 
-    logger_command "OBP sanity check succeeded."
+    logecho "OBP sanity check succeeded."
     kecho "OBP sanity check succeeded."
   else
     #OBP not OK, check if was an user choice otherwise automatically apply (this should be the case called also on first install)
     if [ "$(uci -q get modgui.var.check_obp)" == "0" ]; then
-      logger_command "OBP sanity check FAILED but check_obp set to 0... Not acting"
+      logecho "OBP sanity check FAILED but check_obp set to 0... Not acting"
       kecho "OBP sanity check FAILED but check_obp set to 0... Not acting"
     else
 
       if [ $(cat /proc/$PPID/comm) == "upgradegui" ]; then
-        logger_command "OBP sanity check FAILED but upgrading, postpone planning on next boot..."
+        logecho "OBP sanity check FAILED but upgrading, postpone planning on next boot..."
         kecho "OBP sanity check FAILED but upgrading, postpone planning on next boot..."
         uci set modgui.var.reboot_reason_msg="apply OBP planning"
         uci commit modgui
@@ -337,16 +365,16 @@ check_and_apply_obp() {
       uci set modgui.var.reboot_reason_msg=""
       uci commit modgui
 
-      logger_command "OBP sanity check FAILED start autoplanning..."
+      logecho "OBP sanity check FAILED start autoplanning..."
       kecho "OBP sanity check FAILED start autoplanning..."
 
       if [ "$bootedbank" == "bank_2" ]; then
         # Force erase of bank_1 to have a clean modoverlay
-        logger_command "Erasing bank_1 firmware to prepare modoverlay..."
+        logecho "Erasing bank_1 firmware to prepare modoverlay..."
         kecho "Erasing bank_1 firmware to prepare modoverlay...."
         erase_bank1_reboot "$bootedbank"
       else
-        logger_command "Cloning to bank_2 and checking checksum..."
+        logecho "Cloning to bank_2 and checking checksum..."
         kecho "Cloning to bank_2 and checking checksum..."
         bank1_mtd="/dev/$(get_bank_mtd bank_1)"
         bank2_mtd="/dev/$(get_bank_mtd bank_2)"
@@ -355,13 +383,13 @@ check_and_apply_obp() {
         md5_bank_1=$(md5sum "$bank1_mtd" | awk '{ print $1 }')
         md5_bank_2=$(md5sum "$bank2_mtd" | awk '{ print $1 }')
         if [ "$md5_bank_1" == "$md5_bank_2" ]; then
-          logger_command "Cloning complete, moving to bank_2 overlay..."
+          logecho "Cloning complete, moving to bank_2 overlay..."
           kecho "Cloning complete, moving to bank_2 overlay..."
           # Clean any existing overlay for bank_2 firmware
           rm -rf /overlay/bank_2
           erase_bank1_reboot "$bootedbank"
         else
-          logger_command "Failed cloning bank_1 to bank_2 stopping!"
+          logecho "Failed cloning bank_1 to bank_2 stopping!"
           kecho "Failed cloning bank_1 to bank_2 stopping!"
           exit 1
         fi
@@ -376,20 +404,20 @@ check_full_overlay() {
   bootedbank=$(cat /proc/banktable/booted)
   #Reset if rootfs more than 97% full
   if [ "$overlay_percent" -gt 96 ]; then
-    logger_command "DETECTED FULL ROOTFS... TRYING TO RESTORE..."
+    logecho "DETECTED FULL ROOTFS... TRYING TO RESTORE..."
     kecho "  DETECTED FULL ROOTFS... TRYING TO RESTORE..."
     for dir in /overlay/"$bootedbank"/*; do
       if [ ! "$dir" == "/overlay/$bootedbank/etc" ]; then
-        logger_command "TRYING TO SAVE ROOT BY REMOVING EVERY DIR EXCEPT /etc"
+        logecho "TRYING TO SAVE ROOT BY REMOVING EVERY DIR EXCEPT /etc"
         kecho "TRYING TO SAVE ROOT BY REMOVING EVERY DIR EXCEPT /etc"
         rm -rf "$dir"
       fi
     done
     #Verify if rm did actually remove the files/folders (using /root as check) if not ERASE...
     if [ -d "/overlay/$bootedbank/root" ]; then
-      logger_command "CAN'T REMOVE FILES... INITIALISING FULL ROOTFS ERASE"
+      logecho "CAN'T REMOVE FILES... INITIALISING FULL ROOTFS ERASE"
       kecho "  CAN'T REMOVE FILES... INITIALISING FULL ROOTFS ERASE"
-      logger_command "THIS WILL RESTORE THE MODEM TO FACTORY SETTINGS"
+      logecho "THIS WILL RESTORE THE MODEM TO FACTORY SETTINGS"
       kecho "  THIS WILL RESTORE THE MODEM TO FACTORY SETTINGS"
       mtd erase -r "$overlay_mtdblock"
     fi
@@ -417,7 +445,9 @@ boot() {
 
   logo_project
 
-  logger -s -t 'Root Script' "Checking installation prerequisites, if needed installation will continue after reboot..."
+  logecho_always "Checking installation prerequisites, if needed installation will continue after reboot..."
+
+  create_modgui_log
 
   check_full_overlay
   enable_serial_console
@@ -428,25 +458,29 @@ boot() {
   [ -z "$force" ] && force=0
 
   if [ -f /root/.reapply_due_to_upgrade ]; then
-    logger_command "Upgrade just done Extracting GUI.tar.bz2..."
+    logecho "Upgrade just done Extracting GUI.tar.bz2..."
     kecho "Upgrade just done Extracting GUI.tar.bz2..."
     if [ -f /root/GUI.tar.bz2 ]; then
       bzcat /root/GUI.tar.bz2 | tar -C / -xvf -
       sync
     else
-      logger_command "Extraction FAILED GUI.tar.bz2 NOT FOUND!"
+      logecho "Extraction FAILED GUI.tar.bz2 NOT FOUND!"
       kecho "Extraction FAILED GUI.tar.bz2 NOT FOUND!"
     fi
   fi
 
   if [ $force -eq 1 ] || [ -f /root/.install_gui ]; then
-    logger_command "Force/install flag detected! Reinstalling..."
+    logecho "Force/install flag detected! Reinstalling..."
     kecho "force/install flag detected! Reinstalling..."
     install_gui
+    save_modgui_log
   else
-    logger_command "No force/install flag detected! Doing nothing."
+    logecho "No force/install flag detected! Doing nothing."
     kecho "No force/install flag detected! Doing nothing."
   fi
+
+  # Modgui logs will be deleted on the next boot.
+  sched_remove_modgui_log
 
   ubus send fwupgrade '{ "state": "done" }'
 }
diff --git a/decompressed/gui_file/usr/share/transformer/scripts/upgradegui b/decompressed/gui_file/usr/share/transformer/scripts/upgradegui
--- a/decompressed/gui_file/usr/share/transformer/scripts/upgradegui
+++ b/decompressed/gui_file/usr/share/transformer/scripts/upgradegui
@@ -53,7 +53,7 @@ set_transformer() {
 }
 #################################################
 
-logger_command() {
+logecho() {
   logger -t "Upgrade Script" "$1"
   echo "Upgrade Script" "$1"
 }
@@ -76,7 +76,7 @@ if [ "$1" ]; then
   if [ "$1" == "AutoUpgrade" ]; then
     /usr/share/transformer/scripts/checkver
     if [ "$(uci get modgui.gui.outdated_ver)" == "0" ]; then
-      logger_command "Already at latest version. Aborting upgrade."
+      logecho "Already at latest version. Aborting upgrade."
       exit 0
     fi
     # Enabling alert for the gui about the autoupgrade
@@ -131,7 +131,7 @@ FORCE_SAVE_GUI=0
 
 overlay_available_space=$(df /overlay | sed -n 2p | awk {'{print $4}'})
 if [ "$overlay_available_space" -lt 3000 ]; then
-  logger_command "ERROR: not enough space to complete operation" >&2
+  logecho "ERROR: not enough space to complete operation" >&2
   #Should probably implement some sort of erase here <kevdagoat>
   ubus send fwupgrade '{"state":"done"}'
   exit 1
@@ -141,10 +141,10 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
 
   set_transformer "rpc.system.modgui.executeCommand.state" "Downloading"
 
-  logger_command "Downloading GUI file..."
+  logecho "Downloading GUI file..."
   # Enter /tmp folder
   if ! cd "$WORKING_DIR"; then
-    logger_command "ERROR: Can't access $WORKING_DIR" >&2
+    logecho "ERROR: Can't access $WORKING_DIR" >&2
     ubus send fwupgrade '{"state":"done"}'
     exit 1
   fi
@@ -156,7 +156,7 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
 
   # Download new GUI to /tmp
   if ! $curl $URL_BASE/$FILE_NAME --output $WORKING_DIR/$FILE_NAME; then
-    logger_command "ERROR: Can't find new GUI file" >&2
+    logecho "ERROR: Can't find new GUI file" >&2
     ubus send fwupgrade '{"state":"done"}'
     exit 1
   fi
@@ -172,19 +172,19 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
   if ! grep -q "$downloaded_md5" "$WORKING_DIR/$CHECKSUM_FILE"; then
     rm "$WORKING_DIR/$FILE_NAME"
     rm "$WORKING_DIR/$CHECKSUM_FILE"
-    logger_command "ERROR: File corrupted!!!" >&2
-    logger_command "ERROR: Removing upgrade file and aborting." >&2
+    logecho "ERROR: File corrupted!!!" >&2
+    logecho "ERROR: Removing upgrade file and aborting." >&2
     #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
     ubus send fwupgrade '{"state":"done"}'
     exit 1
   fi
 
-  logger_command "Downloaded GUI with hash: $downloaded_md5"
+  logecho "Downloaded GUI with hash: $downloaded_md5"
 
   if [ "$update_branch" ]; then
     if [ "$update_branch" == "_dev" ] || [ "$update_branch" == "_preview" ]; then
 
-      logger_command "Dev branch detected... Checking for newer version in stable..."
+      logecho "Dev branch detected... Checking for newer version in stable..."
 
       if [ -f "$WORKING_DIR/$STABLE_FILE_NAME" ]; then
         rm "$WORKING_DIR/$STABLE_FILE_NAME"
@@ -193,7 +193,7 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
       # Download stable GUI to /tmp
 
       if ! $curl $URL_BASE/$STABLE_FILE_NAME --output $WORKING_DIR/$STABLE_FILE_NAME; then
-        logger_command "ERROR: Can't find stable GUI file" >&2
+        logecho "ERROR: Can't find stable GUI file" >&2
         rm "$WORKING_DIR/$FILE_NAME"
         rm "$WORKING_DIR/$CHECKSUM_FILE"
         #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
@@ -207,27 +207,27 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
         rm "$WORKING_DIR/$FILE_NAME"
         rm "$WORKING_DIR/$STABLE_FILE_NAME"
         rm "$WORKING_DIR/$CHECKSUM_FILE"
-        logger_command "ERROR: Stable file corrupted!!!" >&2
-        logger_command "ERROR: Removing upgrade file and aborting." >&2
+        logecho "ERROR: Stable file corrupted!!!" >&2
+        logecho "ERROR: Removing upgrade file and aborting." >&2
         #Call a handler here to say fw upgrade failed? eg. ubus send fwupgrade '{"state":"failed"}'
         ubus send fwupgrade '{"state":"done"}'
         exit 1
       fi
 
-      logger_command "Downloaded stable GUI with hash: $stable_md5"
+      logecho "Downloaded stable GUI with hash: $stable_md5"
 
       stable_version="$(cat $WORKING_DIR/$CHECKSUM_FILE | grep $stable_md5 | cut -d' ' -f2)"
       stable_version_norm="$(normalize $stable_version)"
 
-      logger_command "Downloaded Stable version: $stable_version_norm"
+      logecho "Downloaded Stable version: $stable_version_norm"
 
       dev_version="$(cat $WORKING_DIR/$CHECKSUM_FILE | grep $downloaded_md5 | cut -d' ' -f2)"
       dev_version_norm="$(normalize $dev_version)"
 
-      logger_command "Downloaded $update_branch version: $dev_version_norm"
+      logecho "Downloaded $update_branch version: $dev_version_norm"
 
       if [ $(enum $stable_version_norm) -gt $(enum $dev_version_norm) ]; then
-        logger_command "Found newer version in stable branch, using it..."
+        logecho "Found newer version in stable branch, using it..."
         rm "$WORKING_DIR/$FILE_NAME"
         FILE_NAME="$STABLE_FILE_NAME"
         FORCE_SAVE_GUI=1
@@ -237,7 +237,7 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
           saved_stable_md5=$(md5sum $PERMANENT_STORE_DIR/$FILE_NAME | cut -d' ' -f1)
 
           if [ $saved_stable_md5 != $stable_md5 ]; then
-            logger_command "Permanent package md5 is not same of latest Stable GUI. Replacing..."
+            logecho "Permanent package md5 is not same of latest Stable GUI. Replacing..."
             rm "$PERMANENT_STORE_DIR/$FILE_NAME"
             cp $WORKING_DIR/$STABLE_FILE_NAME $PERMANENT_STORE_DIR/
           fi
@@ -248,7 +248,7 @@ if [ ! -f $WORKING_DIR/$FILE_NAME ]; then #Check if file exist as offline upload
     fi
   fi
 else
-  logger_command "Found file in /tmp dir... doing offline upgrade!"
+  logecho "Found file in /tmp dir... doing offline upgrade!"
   #Save gui always as STABLE in offline upgrade as we can't check or download it.
   FORCE_SAVE_GUI=1
 fi
@@ -256,10 +256,10 @@ fi
 set_transformer "rpc.system.modgui.executeCommand.state" "Clearing"
 
 #NOT NEEDED ANYMORE
-#logger_command "Stopping nginx..."
+#logecho "Stopping nginx..."
 #/etc/init.d/nginx stop
 
-logger_command "Cleaning www dir"
+logecho "Cleaning www dir"
 #clean old www dir
 
 for dir in /www/*; do
@@ -286,29 +286,29 @@ done
 
 set_transformer "rpc.system.modgui.executeCommand.state" "Extracting"
 
-logger_command "Extracting file..."
+logecho "Extracting file..."
 # Extract new GUI to /
 bzcat "$WORKING_DIR/$FILE_NAME" |
   tar -C "$TARGET_DIR" -xvf - |
   while read -r line; do
     nfile_extracted=$((nfile_extracted + 1))
     if [ $(($nfile_extracted % 100)) -eq 0 ]; then
-      logger_command "Extracted $nfile_extracted files"
+      logecho "Extracted $nfile_extracted files"
     fi
   done
 
 #Remove deprecated GUI packages if found in /root
 if [ -f /root/GUI_dev.tar.bz2 ]; then
-  logger_command "Deleting /root/GUI_dev.tar.bz2..."
+  logecho "Deleting /root/GUI_dev.tar.bz2..."
   rm /root/GUI_dev.tar.bz2
 fi
 if [ -f /root/GUI.tar.gz ]; then
-  logger_command "Deleting GUI.tar.gz..."
+  logecho "Deleting GUI.tar.gz..."
   rm /root/GUI.tar.gz
 fi
 
 if [ -z "$update_branch" ] || [ $FORCE_SAVE_GUI == 1 ]; then
-  logger_command "Copying file to permanent dir..."
+  logecho "Copying file to permanent dir..."
   #Copy GUI file to permanent dir
   if [ -f "$PERMANENT_STORE_DIR/$FILE_NAME" ]; then
     rm "$PERMANENT_STORE_DIR/$FILE_NAME"
@@ -317,13 +317,13 @@ if [ -z "$update_branch" ] || [ $FORCE_SAVE_GUI == 1 ]; then
 fi
 
 if [ "$update_branch" == "_dev" ] || [ "$update_branch" == "_preview" ]; then
-  logger_command "Saving md5sum of dev gui to /root ..."
+  logecho "Saving md5sum of dev gui to /root ..."
   md5sum "$WORKING_DIR/$FILE_NAME" | cut -d' ' -f1 >/root/gui_dev.md5sum
 fi
 
 sync
 
-logger_command "Running rootdevice script"
+logecho "Running rootdevice script"
 # Run init.d script
 set_transformer "rpc.system.modgui.executeCommand.state" "In Progress"
 /etc/init.d/rootdevice "$rootdevice_call"
@@ -337,4 +337,4 @@ if [ -f "$WORKING_DIR/$CHECKSUM_FILE" ]; then
 fi
 
 ubus send fwupgrade '{"state":"done"}'
-logger_command "Upgrade Done" ConsoleOnly
+logecho "Upgrade Done" ConsoleOnly
